name: Push to Screeps

on:
  push:
    branches:
      - main

jobs:
  push:
    name: Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: write screeps config
        env:
          SCREEPS_EMAIL: ${{ secrets.SCREEPS_EMAIL }}
          SCREEPS_TOKEN: ${{ secrets.SCREEPS_TOKEN }}
        run: |-
          echo "{
            \"main\": {
              \"token\": \"$SCREEPS_TOKEN\",
              \"protocol\": \"https\",
              \"hostname\": \"screeps.com\",
              \"port\": 443,
              \"path\": \"/\",
              \"branch\": \"test\"
            }
          }" > screeps.json

      - name: push
        run: npm run push-main
